services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /home/earthlyeric6/redisdata:/data
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: astroeyes
      POSTGRES_PASSWORD: astroeyes
      POSTGRES_DB: astroeyes_db
    ports:
      - "5432:5432"
    volumes:
      - /home/earthlyeric6/pgdata:/var/lib/postgresql/data
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - /home/earthlyeric6/redis-insight-data:/data
    depends_on:
      - redis
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    